Generation.Excercise.Web/Generation.Excercise.Web/Controllers/DiceGameController.cs
using System.Web.Mvc;

namespace Generation.Excercise.Web.Controllers
{
    public class DiceGameController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Generation.Excercise.Web/Generation.Excercise.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Generation.Excercise.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Generation.Excercise.Web/Generation.Excercise.Web/Controllers/PainterController.cs
using System.Web.Mvc;

namespace Generation.Excercise.Web.Controllers
{
    public class PainterController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Generation.Excercise.Web/Generation.Excercise.Web/Controllers/PokerController.cs
using System.Web.Mvc;

namespace Generation.Excercise.Web.Controllers
{
    public class PokerController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Generation.Excercise.Web/Generation.Excercise.Web/Controllers/ReverserController.cs
using System.Web.Mvc;
using Generation.WordReverser;

namespace Generation.Excercise.Web.Controllers
{
    public class ReverserController : Controller
    {
        private Reverser _reverser;

        public ReverserController()
        {
            _reverser = new Reverser();
        }

        // GET: /<controller>/
        public ActionResult Index()
        {
            return View();
        }

        [ValidateAntiForgeryToken]
        public ActionResult Test(string word)
        {
            return Json(_reverser.Reverse(word));
        }
    }
}

Generation.Excercise.Web/Generation.Excercise.Web/Views/DiceGame/Index.cshtml
@{
    ViewBag.Title = "Reverser";
}

<div class="row">
    <div class="col-md-12">
        <h1>Dice Game</h1>
        <div>
            <p>Uppgiften är att bygga ett tärningsspel där man kan:</p>
            <ul>
                <li>Rulla en tärning och får ett resultat</li>
                <li>Gissa om nästa kast är högre eller lägre än föregående kast</li>
                <li>Gissar man rätt så får man en poäng och spelet ska hålla koll på hur många poäng man får</li>
                <li>Spelet tar slut när man gissar fel. Då ska poängen visas</li>
            </ul>
        </div>
        <pre><code class="cs">//Potentiella komponenter...
public class Game
{
}
            
public class Dice : ...
</code></pre>

    </div>

</div>

Generation.Excercise.Web/Generation.Excercise.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Generation.Excercise.Web/Generation.Excercise.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Generation.Excercise.Web/Generation.Excercise.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}


<div class="row">
    <div class="col-md-4">
        <h2>Uppgifter</h2>
        <ul>
            <li>
                @Html.ActionLink("Reverser", "Index", "Reverser")
            </li>
            <li>
                @Html.ActionLink("Dice Game", "Index", "DiceGame")
            </li>
            <li>
                @Html.ActionLink("Painter", "Index", "Painter")
            </li>
            <li>
                @Html.ActionLink("Poker game", "Index", "Poker")
            </li>
        </ul>
    </div>
</div>

Generation.Excercise.Web/Generation.Excercise.Web/Views/Painter/Index.cshtml
@{
    ViewBag.Title = "Painter";
}

<div class="row">
    <div class="col-md-12">
        <h1>Painter</h1>
        <div>
            <p>Uppgiften är att bygga stöd för det nyetablerade företaget FFCG Painter. I måleriet ska man kunna:</p>
            <ul>
                <li>Måla en bil i önskad färg</li>
                <li>Måla en buss i önskad färg</li>
                <li>Måla ett tåg i önskad färg</li>
                <li>Måla ett flygplan i önskad färg</li>
                <li>Vara beredd på att expandera då våra analyser säger att kundbasen för företag som målar fordon kommer öka rejält</li>
            </ul>
        </div>
        <pre><code class="cs">//Potentiella komponenter...

//using System.Drawing; <- innehåller klassen Color

public class Painter
{
    public void Paint(..., Color color)
}
            
public class Car : ...
</code></pre>

    </div>

</div>

Generation.Excercise.Web/Generation.Excercise.Web/Views/Poker/Index.cshtml
@{
    ViewBag.Title = "Poker Game!";
}

<div class="row">
    <div class="col-md-12">
        <h1>Poker Game!</h1>
        <div>
            <ul>
                <li>En klassisk kortlek</li>
                <li>Ska kunna blandas</li>
                <li>Ska kunna dela ut händer (5 kort)</li>
                <li>Händerna ska kunna inspekteras efter mönster (färg etc)</li>
                <li>När alla kort är slut ska den blandas om</li>
                <li>Händer ska delas ut till någon får en straight flush</li>
                <li>Antal händer som delades ut ska räknas</li>
            </ul>
        </div>
        <pre><code class="cs">//Potentiella komponenter...

public enum Suit
{
    Hearts,
    Clubs,
    Diamonds,
    Spades
}
</code></pre>

    </div>

</div>

Generation.Excercise.Web/Generation.Excercise.Web/Views/Reverser/Index.cshtml
@{
    ViewBag.Title = "Reverser";
}

<div class="row">
    <div class="col-md-12">
        <h1>Reverser</h1>
        <div>
            <p>Uppgiften är att bygga en Text Reverser som ska kunna göra följande:</p>
            <ul>
                <li>Vända på bokstäverna i ett ord</li>
                <li>Vända på bokstäverna i varje ord i en mening, men orden ska behålla sin ursprungliga plats</li>
                <li>Båda ovan, men behålla positionerna på stor/liten bokstav, dvs börjar ett ord med stor bokstav ska det fortfarande göra det när det är vänt</li>
            </ul>
            <p>
                Ni kommer få några tester att utgå ifrån:
            </p>
        </div>
        <pre><code class="cs">private Reverser _reverser;

[TestInitialize]
public void SetUp()
{
    _reverser = new Reverser();
}

[TestMethod]
public void Should_reverse_one_word()
{
    string result = _reverser.Reverse("hello");
    Assert.AreEqual("olleh", result);
}

[TestMethod]
public void Should_reverse_words_in_sentence_and_keep_them_in_place()
{
    string result = _reverser.Reverse("hello world");
    Assert.AreEqual("olleh dlrow", result);
}

[TestMethod]
public void Should_keep_uppercase_positions()
{
    string result = _reverser.Reverse("For the Win");
    Assert.AreEqual("Rof eht Niw", result);
}</code>
</pre>

    </div>

</div>

<!--
<div class="row">
    <div class="col-md-6">
        <div class="input-group">
            <input id="input_text" type="text" class="form-control" placeholder="Testa en mening...">
            <span class="input-group-btn">
                <button id="test" class="btn btn-default" type="button">Testa!</button>
            </span>
        </div>
    </div>
    <div class="col-md-6">
        <div>
            <h3><span class="result"></span></h3>
        </div>
    </div>
</div>-->

@section scripts
{
    <script type="text/javascript">
        $('#input_text').keypress(function (e) {
            if (e.which == 13) {
                $(this).blur();
                $('#test').focus().click();
            }
        });
        $('#test')
            .click(function () {
                var inputText = $("#input_text").val();

                if (inputText === '') {
                    $('.result').text('');
                }

                else {

                    $.ajax({
                        type: "GET",
                        url: "reverser/test",
                        data: { word: inputText },
                        dataType: "json",
                        error: function (xhr, status, error) {
                            // you may need to handle me if the json is invalid
                            // this is the ajax object
                        },
                        success: function (json) {
                            $('.result').text(json);
                        }
                    });
                }

                $('#input_text').focus();

            });

        $('#input_text').focus();
    </script>
}

Generation.Excercise.Web/Generation.Excercise.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Generation: @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("FFCG - Generation", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()       
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/highlight")
    @RenderSection("scripts", required: false)
    <script>hljs.initHighlightingOnLoad();</script>
</body>
</html>